component_depth: 1
languages: 
- java
exclude:
- ./bin/.*
- ./bin/com/.*
- ./bin/com/opensymphony/.*
- ./bin/com/opensymphony/oscache/.*
- ./bin/com/opensymphony/oscache/base/.*
- ./bin/com/opensymphony/oscache/base/algorithm/.*
- ./bin/com/opensymphony/oscache/base/events/.*
- ./bin/com/opensymphony/oscache/base/persistence/.*
- ./bin/com/opensymphony/oscache/extra/.*
- ./bin/com/opensymphony/oscache/general/.*
- ./bin/com/opensymphony/oscache/plugins/.*
- ./bin/com/opensymphony/oscache/plugins/clustersupport/.*
- ./bin/com/opensymphony/oscache/plugins/diskpersistence/.*
- ./bin/com/opensymphony/oscache/util/.*
- ./bin/com/opensymphony/oscache/web/.*
- ./bin/com/opensymphony/oscache/web/filter/.*
- ./bin/com/opensymphony/oscache/web/tag/.*
- ./docs/.*
- ./docs/api/.*
- ./docs/api/com/.*
- ./docs/api/com/opensymphony/.*
- ./docs/api/com/opensymphony/oscache/.*
- ./docs/api/com/opensymphony/oscache/base/.*
- ./docs/api/com/opensymphony/oscache/base/algorithm/.*
- ./docs/api/com/opensymphony/oscache/base/algorithm/class-use/.*
- ./docs/api/com/opensymphony/oscache/base/class-use/.*
- ./docs/api/com/opensymphony/oscache/base/events/.*
- ./docs/api/com/opensymphony/oscache/base/events/class-use/.*
- ./docs/api/com/opensymphony/oscache/base/persistence/.*
- ./docs/api/com/opensymphony/oscache/base/persistence/class-use/.*
- ./docs/api/com/opensymphony/oscache/extra/.*
- ./docs/api/com/opensymphony/oscache/extra/class-use/.*
- ./docs/api/com/opensymphony/oscache/general/.*
- ./docs/api/com/opensymphony/oscache/general/class-use/.*
- ./docs/api/com/opensymphony/oscache/plugins/.*
- ./docs/api/com/opensymphony/oscache/plugins/clustersupport/.*
- ./docs/api/com/opensymphony/oscache/plugins/clustersupport/class-use/.*
- ./docs/api/com/opensymphony/oscache/plugins/diskpersistence/.*
- ./docs/api/com/opensymphony/oscache/plugins/diskpersistence/class-use/.*
- ./docs/api/com/opensymphony/oscache/util/.*
- ./docs/api/com/opensymphony/oscache/util/class-use/.*
- ./docs/api/com/opensymphony/oscache/web/.*
- ./docs/api/com/opensymphony/oscache/web/class-use/.*
- ./docs/api/com/opensymphony/oscache/web/filter/.*
- ./docs/api/com/opensymphony/oscache/web/filter/class-use/.*
- ./docs/api/com/opensymphony/oscache/web/tag/.*
- ./docs/api/com/opensymphony/oscache/web/tag/class-use/.*
- ./docs/clover/.*
- ./docs/clover/com/.*
- ./docs/clover/com/opensymphony/.*
- ./docs/clover/com/opensymphony/oscache/.*
- ./docs/clover/com/opensymphony/oscache/base/.*
- ./docs/clover/com/opensymphony/oscache/base/algorithm/.*
- ./docs/clover/com/opensymphony/oscache/base/events/.*
- ./docs/clover/com/opensymphony/oscache/base/persistence/.*
- ./docs/clover/com/opensymphony/oscache/extra/.*
- ./docs/clover/com/opensymphony/oscache/general/.*
- ./docs/clover/com/opensymphony/oscache/plugins/.*
- ./docs/clover/com/opensymphony/oscache/plugins/clustersupport/.*
- ./docs/clover/com/opensymphony/oscache/plugins/diskpersistence/.*
- ./docs/clover/com/opensymphony/oscache/util/.*
- ./docs/clover/com/opensymphony/oscache/web/.*
- ./docs/clover/com/opensymphony/oscache/web/filter/.*
- ./docs/clover/com/opensymphony/oscache/web/tag/.*
- ./docs/clover/img/.*
- ./docs/dependencies/.*
- ./docs/junit/.*
- ./docs/junit/com/.*
- ./docs/junit/com/opensymphony/.*
- ./docs/junit/com/opensymphony/oscache/.*
- ./docs/junit/com/opensymphony/oscache/base/.*
- ./docs/junit/com/opensymphony/oscache/base/algorithm/.*
- ./docs/junit/com/opensymphony/oscache/base/events/.*
- ./docs/junit/com/opensymphony/oscache/extra/.*
- ./docs/junit/com/opensymphony/oscache/general/.*
- ./docs/wiki/.*
- ./docs/wiki/Statistics_attachments/.*
- ./docs/wiki/border/.*
- ./docs/wiki/icons/.*
- ./docs/wiki/icons/emoticons/.*
- ./docs/wiki/styles/.*
- ./etc/.*
- ./lib/.*
